platform :ios, ‘9.0’
use_frameworks!
target 'YZ_Four' do
    
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'AFNetworking', '~> 3.2.0'	
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'MJRefresh'
   pod 'MJExtension'		  	 
   pod 'DZNEmptyDataSet'
   pod 'ReactiveObjC', '~> 2.1.0'
   pod 'SDCycleScrollView','~> 1.75'
end
